### ISSUE TITLE
[typo] in 'PyMC3 with labeled coords and dims'

### ISSUE THREAD

**Issue by OlafHaag** [OriolAbril/oriol_unraveled#2]
https://github.com/OriolAbril/oriol_unraveled/blob/main/_notebooks/2020-09-22-pymc3-arviz.ipynb

The line
> Level: observations can correspond to the basement of the first floor

should probably read

> Level: observations can correspond to the basement or the first floor

*of* -> *or*

**Comment by OriolAbril** [comment]
Thanks!
